test:
  adapter: postgresql
  database: veoveo_test
  username: <%= ENV['USER'] %>
  pool: 5
  encoding: unicode
  host: localhost
development:
  adapter: postgresql
  database: veoveo_development
  username: <%= ENV['USER'] %>
  pool: 5
  encoding: unicode
  host: localhost
production:
  adapter: postgresql
  database: veoveo_production
  username: <%= ENV['USER'] %>
  pool: 5
  encoding: unicode
  host: localhost
